name: Build Workflow
on: workflow_dispatch

jobs:
  build:
    name: Build job
    runs-on: ubuntu-latest
    uses: actions/checkout@v1    

  - name: Build with Maven
    run: mvn -B test

    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
